import {
  Accessibility,
  Apple,
  Bell,
  BookOpen,
  Building,
  Building2,
  Bus,
  Circle,
  CircleDot,
  Cloud,
  Coffee,
  Dices,
  Dog,
  Droplets,
  Dumbbell,
  Film,
  Flag,
  Flame,
  Flower2,
  Footprints,
  GripVertical,
  Hammer,
  Hand,
  Home,
  type LucideIcon,
  LockKeyhole,
  MapPin,
  Music,
  PawPrint,
  Plug,
  Scissors,
  Sofa,
  Sprout,
  Target,
  Truck,
  Umbrella,
  Utensils,
  UtensilsCrossed,
  Waves,
  Wrench,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  apple: Apple,
  bell: Bell,
  'book-open': BookOpen,
  building: Building,
  'building-2': Building2,
  bus: Bus,
  circle: Circle,
  'circle-dot': CircleDot,
  cloud: Cloud,
  coffee: Coffee,
  dices: Dices,
  dog: Dog,
  droplets: Droplets,
  dumbbell: Dumbbell,
  film: Film,
  flag: Flag,
  flame: Flame,
  'flower-2': Flower2,
  footprints: Footprints,
  'grip-vertical': GripVertical,
  hammer: Hammer,
  hand: Hand,
  home: Home,
  'lock-keyhole': LockKeyhole,
  music: Music,
  'paw-print': PawPrint,
  plug: Plug,
  scissors: Scissors,
  sofa: Sofa,
  sprout: Sprout,
  target: Target,
  truck: Truck,
  umbrella: Umbrella,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  waves: Waves,
  wrench: Wrench,
};

export function FacilityIcon({
  name,
  size = 20,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Comp = ICONS[name] ?? MapPin;
  return <Comp size={size} className={className} />;
}
